//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Journey.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Journey.Resources.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while getting Account data.
        /// </summary>
        internal static string Account_ErrorGetData {
            get {
                return ResourceManager.GetString("Account_ErrorGetData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journey.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        internal static string Camera {
            get {
                return ResourceManager.GetString("Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera not supported in your device.
        /// </summary>
        internal static string Camera_NotSupported {
            get {
                return ResourceManager.GetString("Camera_NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already Existing challenge is up and running.
        /// </summary>
        internal static string Challenge_AlreadyExists {
            get {
                return ResourceManager.GetString("Challenge_AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve Challenge.
        /// </summary>
        internal static string Challenge_Approve {
            get {
                return ResourceManager.GetString("Challenge_Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge will be started when your friend approve.
        /// </summary>
        internal static string Challenge_ApproveMessage {
            get {
                return ResourceManager.GetString("Challenge_ApproveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose workout place.
        /// </summary>
        internal static string Challenge_ChooseYourWorkoutPlace {
            get {
                return ResourceManager.GetString("Challenge_ChooseYourWorkoutPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge.
        /// </summary>
        internal static string Challenge_Comepete {
            get {
                return ResourceManager.GetString("Challenge_Comepete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date should be greater than Start date.
        /// </summary>
        internal static string Challenge_DataValidation {
            get {
                return ResourceManager.GetString("Challenge_DataValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Challenge_Edit {
            get {
                return ResourceManager.GetString("Challenge_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        internal static string Challenge_EndDate {
            get {
                return ResourceManager.GetString("Challenge_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercises.
        /// </summary>
        internal static string Challenge_Exercises {
            get {
                return ResourceManager.GetString("Challenge_Exercises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Challenge.
        /// </summary>
        internal static string Challenge_Header {
            get {
                return ResourceManager.GetString("Challenge_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose workout place.
        /// </summary>
        internal static string Challenge_LocationMust {
            get {
                return ResourceManager.GetString("Challenge_LocationMust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Exercise this Month.
        /// </summary>
        internal static string Challenge_NumberOfExercies {
            get {
                return ResourceManager.GetString("Challenge_NumberOfExercies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Challenge.
        /// </summary>
        internal static string Challenge_Start {
            get {
                return ResourceManager.GetString("Challenge_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string Challenge_StartDate {
            get {
                return ResourceManager.GetString("Challenge_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Challenge.
        /// </summary>
        internal static string Challenge_View {
            get {
                return ResourceManager.GetString("Challenge_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winner till now in.
        /// </summary>
        internal static string Challenge_Winner {
            get {
                return ResourceManager.GetString("Challenge_Winner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Comments.
        /// </summary>
        internal static string Comments_NoComments {
            get {
                return ResourceManager.GetString("Comments_NoComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Weight.
        /// </summary>
        internal static string CurrentWeight {
            get {
                return ResourceManager.GetString("CurrentWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ago.
        /// </summary>
        internal static string Date_Ago {
            get {
                return ResourceManager.GetString("Date_Ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        internal static string Date_Day {
            get {
                return ResourceManager.GetString("Date_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        internal static string Date_Days {
            get {
                return ResourceManager.GetString("Date_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hr.
        /// </summary>
        internal static string Date_Hour {
            get {
                return ResourceManager.GetString("Date_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hrs.
        /// </summary>
        internal static string Date_Hours {
            get {
                return ResourceManager.GetString("Date_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to just now.
        /// </summary>
        internal static string Date_JustNow {
            get {
                return ResourceManager.GetString("Date_JustNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min.
        /// </summary>
        internal static string Date_Minute {
            get {
                return ResourceManager.GetString("Date_Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mins.
        /// </summary>
        internal static string Date_Minutes {
            get {
                return ResourceManager.GetString("Date_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to month.
        /// </summary>
        internal static string Date_Month {
            get {
                return ResourceManager.GetString("Date_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to months.
        /// </summary>
        internal static string Date_Months {
            get {
                return ResourceManager.GetString("Date_Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to secs.
        /// </summary>
        internal static string Date_Seconds {
            get {
                return ResourceManager.GetString("Date_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string Date_Today {
            get {
                return ResourceManager.GetString("Date_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomorrow.
        /// </summary>
        internal static string Date_Tomorrow {
            get {
                return ResourceManager.GetString("Date_Tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yr.
        /// </summary>
        internal static string Date_Year {
            get {
                return ResourceManager.GetString("Date_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yrs.
        /// </summary>
        internal static string Date_Years {
            get {
                return ResourceManager.GetString("Date_Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw.
        /// </summary>
        internal static string Draw {
            get {
                return ResourceManager.GetString("Draw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        internal static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Home_LoginAction {
            get {
                return ResourceManager.GetString("Home_LoginAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Your new challenge.
        /// </summary>
        internal static string Home_StartNewChallenge {
            get {
                return ResourceManager.GetString("Home_StartNewChallenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello Mostafa.
        /// </summary>
        internal static string Home_WelcomeMessage {
            get {
                return ResourceManager.GetString("Home_WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0}, Want to share an update.
        /// </summary>
        internal static string Home_WelcomeMessage_Login {
            get {
                return ResourceManager.GetString("Home_WelcomeMessage_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to share an update.
        /// </summary>
        internal static string Home_WelcomeMessage_Logout {
            get {
                return ResourceManager.GetString("Home_WelcomeMessage_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilometers.
        /// </summary>
        internal static string KM {
            get {
                return ResourceManager.GetString("KM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is this your default workout place?.
        /// </summary>
        internal static string Location_DefaultLocationTitle {
            get {
                return ResourceManager.GetString("Location_DefaultLocationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Places.
        /// </summary>
        internal static string Location_NoPlaces {
            get {
                return ResourceManager.GetString("Location_NoPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cant login right now!.
        /// </summary>
        internal static string Login_CantLoginMessage {
            get {
                return ResourceManager.GetString("Login_CantLoginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Login_CantLoginTitle {
            get {
                return ResourceManager.GetString("Login_CantLoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update your measurments.
        /// </summary>
        internal static string Measurments_Message {
            get {
                return ResourceManager.GetString("Measurments_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        internal static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while uploading your post.
        /// </summary>
        internal static string NewPost_NewPostError {
            get {
                return ResourceManager.GetString("NewPost_NewPostError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Say something about this moment.
        /// </summary>
        internal static string NewPost_NewPostFeedPlaceholder {
            get {
                return ResourceManager.GetString("NewPost_NewPostFeedPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to Post.
        /// </summary>
        internal static string NewPost_NewPostMessage {
            get {
                return ResourceManager.GetString("NewPost_NewPostMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload pictures/Video.
        /// </summary>
        internal static string NewPost_UploadMedia {
            get {
                return ResourceManager.GetString("NewPost_UploadMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} wants to challenge you.
        /// </summary>
        internal static string Notification_ChallengeRequestMessage {
            get {
                return ResourceManager.GetString("Notification_ChallengeRequestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge Request.
        /// </summary>
        internal static string Notification_ChallengeRequestTitle {
            get {
                return ResourceManager.GetString("Notification_ChallengeRequestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Notifcations.
        /// </summary>
        internal static string Notification_NoNotifications {
            get {
                return ResourceManager.GetString("Notification_NoNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Video.
        /// </summary>
        internal static string PickVideo {
            get {
                return ResourceManager.GetString("PickVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Post_Delete {
            get {
                return ResourceManager.GetString("Post_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while deleting your post.
        /// </summary>
        internal static string Post_DeleteError {
            get {
                return ResourceManager.GetString("Post_DeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  What action you need.
        /// </summary>
        internal static string Post_DeleteOrReportMessage {
            get {
                return ResourceManager.GetString("Post_DeleteOrReportMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check in !.
        /// </summary>
        internal static string Post_LocationMust {
            get {
                return ResourceManager.GetString("Post_LocationMust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Posts.
        /// </summary>
        internal static string Post_NoPosts {
            get {
                return ResourceManager.GetString("Post_NoPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        internal static string Post_Report {
            get {
                return ResourceManager.GetString("Post_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your report has been sent.
        /// </summary>
        internal static string Post_ReportSentMessage {
            get {
                return ResourceManager.GetString("Post_ReportSentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent.
        /// </summary>
        internal static string Post_ReportSentTitle {
            get {
                return ResourceManager.GetString("Post_ReportSentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one image is required.
        /// </summary>
        internal static string Post_UploadImageMust {
            get {
                return ResourceManager.GetString("Post_UploadImageMust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        internal static string Profile_Edit {
            get {
                return ResourceManager.GetString("Profile_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Monlthly Goal.
        /// </summary>
        internal static string Profile_SetMonthlyGoal {
            get {
                return ResourceManager.GetString("Profile_SetMonthlyGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Measurments.
        /// </summary>
        internal static string Profile_UpdateMeasurment {
            get {
                return ResourceManager.GetString("Profile_UpdateMeasurment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for friends.
        /// </summary>
        internal static string SearchFriends_Placholder {
            get {
                return ResourceManager.GetString("SearchFriends_Placholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Video.
        /// </summary>
        internal static string TakeVideo {
            get {
                return ResourceManager.GetString("TakeVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Times.
        /// </summary>
        internal static string Times {
            get {
                return ResourceManager.GetString("Times", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string UpdateProfile_Finish {
            get {
                return ResourceManager.GetString("UpdateProfile_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string UpdateProfile_FirstName {
            get {
                return ResourceManager.GetString("UpdateProfile_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must have First name.
        /// </summary>
        internal static string UpdateProfile_FirstNameRequired {
            get {
                return ResourceManager.GetString("UpdateProfile_FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must have Profile picture.
        /// </summary>
        internal static string UpdateProfile_ImageRequired {
            get {
                return ResourceManager.GetString("UpdateProfile_ImageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string UpdateProfile_LastName {
            get {
                return ResourceManager.GetString("UpdateProfile_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string UpdateProfile_Upload {
            get {
                return ResourceManager.GetString("UpdateProfile_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update your intial information.
        /// </summary>
        internal static string UpdateProfile_Welcome {
            get {
                return ResourceManager.GetString("UpdateProfile_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick from Photo/ Gallery.
        /// </summary>
        internal static string UploadPhoto_Message {
            get {
                return ResourceManager.GetString("UploadPhoto_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload your profile picture.
        /// </summary>
        internal static string UploadPhoto_Title {
            get {
                return ResourceManager.GetString("UploadPhoto_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
