//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Journey.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Journey.Resources.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Home_LoginAction {
            get {
                return ResourceManager.GetString("Home_LoginAction", resourceCulture);
            }
        }
        
        internal static string Home_WelcomeMessage {
            get {
                return ResourceManager.GetString("Home_WelcomeMessage", resourceCulture);
            }
        }
        
        internal static string Login_CantLoginMessage {
            get {
                return ResourceManager.GetString("Login_CantLoginMessage", resourceCulture);
            }
        }
        
        internal static string Login_CantLoginTitle {
            get {
                return ResourceManager.GetString("Login_CantLoginTitle", resourceCulture);
            }
        }
        
        internal static string UpdateProfile_Finish {
            get {
                return ResourceManager.GetString("UpdateProfile_Finish", resourceCulture);
            }
        }
        
        internal static string UpdateProfile_FirstName {
            get {
                return ResourceManager.GetString("UpdateProfile_FirstName", resourceCulture);
            }
        }
        
        internal static string UpdateProfile_LastName {
            get {
                return ResourceManager.GetString("UpdateProfile_LastName", resourceCulture);
            }
        }
        
        internal static string UpdateProfile_Upload {
            get {
                return ResourceManager.GetString("UpdateProfile_Upload", resourceCulture);
            }
        }
        
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        internal static string UpdateProfile_FirstNameRequired {
            get {
                return ResourceManager.GetString("UpdateProfile_FirstNameRequired", resourceCulture);
            }
        }
        
        internal static string UpdateProfile_ImageRequired {
            get {
                return ResourceManager.GetString("UpdateProfile_ImageRequired", resourceCulture);
            }
        }
        
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        internal static string UpdateProfile_Welcome {
            get {
                return ResourceManager.GetString("UpdateProfile_Welcome", resourceCulture);
            }
        }
        
        internal static string Camera {
            get {
                return ResourceManager.GetString("Camera", resourceCulture);
            }
        }
        
        internal static string TakeVideo {
            get {
                return ResourceManager.GetString("TakeVideo", resourceCulture);
            }
        }
        
        internal static string PickVideo {
            get {
                return ResourceManager.GetString("PickVideo", resourceCulture);
            }
        }
        
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        internal static string Challenge_Compete {
            get {
                return ResourceManager.GetString("Challenge_Compete", resourceCulture);
            }
        }
        
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        internal static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string UploadPhoto_Title {
            get {
                return ResourceManager.GetString("UploadPhoto_Title", resourceCulture);
            }
        }
        
        internal static string UploadPhoto_Message {
            get {
                return ResourceManager.GetString("UploadPhoto_Message", resourceCulture);
            }
        }
        
        internal static string NewPost_NewPostMessage {
            get {
                return ResourceManager.GetString("NewPost_NewPostMessage", resourceCulture);
            }
        }
        
        internal static string NewPost_NewPostError {
            get {
                return ResourceManager.GetString("NewPost_NewPostError", resourceCulture);
            }
        }
        
        internal static string NewPost_UploadMedia {
            get {
                return ResourceManager.GetString("NewPost_UploadMedia", resourceCulture);
            }
        }
        
        internal static string NewPost_NewPostFeedPlaceholder {
            get {
                return ResourceManager.GetString("NewPost_NewPostFeedPlaceholder", resourceCulture);
            }
        }
        
        internal static string Home_WelcomeMessage_Login {
            get {
                return ResourceManager.GetString("Home_WelcomeMessage_Login", resourceCulture);
            }
        }
        
        internal static string Home_WelcomeMessage_Logout {
            get {
                return ResourceManager.GetString("Home_WelcomeMessage_Logout", resourceCulture);
            }
        }
        
        internal static string Date_Year {
            get {
                return ResourceManager.GetString("Date_Year", resourceCulture);
            }
        }
        
        internal static string Date_Years {
            get {
                return ResourceManager.GetString("Date_Years", resourceCulture);
            }
        }
        
        internal static string Date_Month {
            get {
                return ResourceManager.GetString("Date_Month", resourceCulture);
            }
        }
        
        internal static string Date_Months {
            get {
                return ResourceManager.GetString("Date_Months", resourceCulture);
            }
        }
        
        internal static string Date_Day {
            get {
                return ResourceManager.GetString("Date_Day", resourceCulture);
            }
        }
        
        internal static string Date_Days {
            get {
                return ResourceManager.GetString("Date_Days", resourceCulture);
            }
        }
        
        internal static string Date_Hour {
            get {
                return ResourceManager.GetString("Date_Hour", resourceCulture);
            }
        }
        
        internal static string Date_Hours {
            get {
                return ResourceManager.GetString("Date_Hours", resourceCulture);
            }
        }
        
        internal static string Date_Minute {
            get {
                return ResourceManager.GetString("Date_Minute", resourceCulture);
            }
        }
        
        internal static string Date_Minutes {
            get {
                return ResourceManager.GetString("Date_Minutes", resourceCulture);
            }
        }
        
        internal static string Date_Seconds {
            get {
                return ResourceManager.GetString("Date_Seconds", resourceCulture);
            }
        }
        
        internal static string Date_JustNow {
            get {
                return ResourceManager.GetString("Date_JustNow", resourceCulture);
            }
        }
        
        internal static string Date_Today {
            get {
                return ResourceManager.GetString("Date_Today", resourceCulture);
            }
        }
        
        internal static string Date_Tomorrow {
            get {
                return ResourceManager.GetString("Date_Tomorrow", resourceCulture);
            }
        }
        
        internal static string Date_Ago {
            get {
                return ResourceManager.GetString("Date_Ago", resourceCulture);
            }
        }
        
        internal static string Account_ErrorGetData {
            get {
                return ResourceManager.GetString("Account_ErrorGetData", resourceCulture);
            }
        }
        
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        internal static string Post_Delete {
            get {
                return ResourceManager.GetString("Post_Delete", resourceCulture);
            }
        }
        
        internal static string Post_DeleteError {
            get {
                return ResourceManager.GetString("Post_DeleteError", resourceCulture);
            }
        }
        
        internal static string SearchFriends_Placholder {
            get {
                return ResourceManager.GetString("SearchFriends_Placholder", resourceCulture);
            }
        }
        
        internal static string Challenge_Comepete {
            get {
                return ResourceManager.GetString("Challenge_Comepete", resourceCulture);
            }
        }
        
        internal static string Challenge_FriendHasActiveChallenge {
            get {
                return ResourceManager.GetString("Challenge_FriendHasActiveChallenge", resourceCulture);
            }
        }
        
        internal static string Challenge_DataValidation {
            get {
                return ResourceManager.GetString("Challenge_DataValidation", resourceCulture);
            }
        }
        
        internal static string Challenge_Start {
            get {
                return ResourceManager.GetString("Challenge_Start", resourceCulture);
            }
        }
        
        internal static string Challenge_Approve {
            get {
                return ResourceManager.GetString("Challenge_Approve", resourceCulture);
            }
        }
        
        internal static string Challenge_ApproveMessage {
            get {
                return ResourceManager.GetString("Challenge_ApproveMessage", resourceCulture);
            }
        }
        
        internal static string Challenge_UpdateKMLog {
            get {
                return ResourceManager.GetString("Challenge_UpdateKMLog", resourceCulture);
            }
        }
        
        internal static string Challenge_Exercsing {
            get {
                return ResourceManager.GetString("Challenge_Exercsing", resourceCulture);
            }
        }
        
        internal static string Challenge_LocationMust {
            get {
                return ResourceManager.GetString("Challenge_LocationMust", resourceCulture);
            }
        }
        
        internal static string Challenge_View {
            get {
                return ResourceManager.GetString("Challenge_View", resourceCulture);
            }
        }
        
        internal static string Challenge_StartDate {
            get {
                return ResourceManager.GetString("Challenge_StartDate", resourceCulture);
            }
        }
        
        internal static string Challenge_Edit {
            get {
                return ResourceManager.GetString("Challenge_Edit", resourceCulture);
            }
        }
        
        internal static string Challenge_EndDate {
            get {
                return ResourceManager.GetString("Challenge_EndDate", resourceCulture);
            }
        }
        
        internal static string Challenge_Header {
            get {
                return ResourceManager.GetString("Challenge_Header", resourceCulture);
            }
        }
        
        internal static string Challenge_NumberOfExercies {
            get {
                return ResourceManager.GetString("Challenge_NumberOfExercies", resourceCulture);
            }
        }
        
        internal static string Times {
            get {
                return ResourceManager.GetString("Times", resourceCulture);
            }
        }
        
        internal static string Challenge_AlreadyExists {
            get {
                return ResourceManager.GetString("Challenge_AlreadyExists", resourceCulture);
            }
        }
        
        internal static string Post_Report {
            get {
                return ResourceManager.GetString("Post_Report", resourceCulture);
            }
        }
        
        internal static string Post_DeleteOrReportMessage {
            get {
                return ResourceManager.GetString("Post_DeleteOrReportMessage", resourceCulture);
            }
        }
        
        internal static string Camera_NotSupported {
            get {
                return ResourceManager.GetString("Camera_NotSupported", resourceCulture);
            }
        }
        
        internal static string Post_UploadImageMust {
            get {
                return ResourceManager.GetString("Post_UploadImageMust", resourceCulture);
            }
        }
        
        internal static string Post_ReportSentMessage {
            get {
                return ResourceManager.GetString("Post_ReportSentMessage", resourceCulture);
            }
        }
        
        internal static string Post_ReportSentTitle {
            get {
                return ResourceManager.GetString("Post_ReportSentTitle", resourceCulture);
            }
        }
        
        internal static string Profile_SetMonthlyGoal {
            get {
                return ResourceManager.GetString("Profile_SetMonthlyGoal", resourceCulture);
            }
        }
        
        internal static string Profile_UpdateMeasurment {
            get {
                return ResourceManager.GetString("Profile_UpdateMeasurment", resourceCulture);
            }
        }
        
        internal static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        internal static string Measurments_Message {
            get {
                return ResourceManager.GetString("Measurments_Message", resourceCulture);
            }
        }
        
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        internal static string Profile_Edit {
            get {
                return ResourceManager.GetString("Profile_Edit", resourceCulture);
            }
        }
        
        internal static string CurrentWeight {
            get {
                return ResourceManager.GetString("CurrentWeight", resourceCulture);
            }
        }
        
        internal static string Home_StartNewChallenge {
            get {
                return ResourceManager.GetString("Home_StartNewChallenge", resourceCulture);
            }
        }
        
        internal static string Location_DefaultLocationTitle {
            get {
                return ResourceManager.GetString("Location_DefaultLocationTitle", resourceCulture);
            }
        }
        
        internal static string Notification_ChallengeRequestTitle {
            get {
                return ResourceManager.GetString("Notification_ChallengeRequestTitle", resourceCulture);
            }
        }
        
        internal static string Notification_ChallengeRequestMessage {
            get {
                return ResourceManager.GetString("Notification_ChallengeRequestMessage", resourceCulture);
            }
        }
        
        internal static string Notification_NoNotifications {
            get {
                return ResourceManager.GetString("Notification_NoNotifications", resourceCulture);
            }
        }
        
        internal static string Notification_NotificationHeader {
            get {
                return ResourceManager.GetString("Notification_NotificationHeader", resourceCulture);
            }
        }
        
        internal static string Notification_FriendRequestHeader {
            get {
                return ResourceManager.GetString("Notification_FriendRequestHeader", resourceCulture);
            }
        }
        
        internal static string Home_NoPost {
            get {
                return ResourceManager.GetString("Home_NoPost", resourceCulture);
            }
        }
        
        internal static string Post_NoPosts {
            get {
                return ResourceManager.GetString("Post_NoPosts", resourceCulture);
            }
        }
        
        internal static string Challenge_Exercises {
            get {
                return ResourceManager.GetString("Challenge_Exercises", resourceCulture);
            }
        }
        
        internal static string Challenge_Winner {
            get {
                return ResourceManager.GetString("Challenge_Winner", resourceCulture);
            }
        }
        
        internal static string Challenge_ChooseYourWorkoutPlace {
            get {
                return ResourceManager.GetString("Challenge_ChooseYourWorkoutPlace", resourceCulture);
            }
        }
        
        internal static string KM {
            get {
                return ResourceManager.GetString("KM", resourceCulture);
            }
        }
        
        internal static string Kcal {
            get {
                return ResourceManager.GetString("Kcal", resourceCulture);
            }
        }
        
        internal static string Friends_FollowFriend {
            get {
                return ResourceManager.GetString("Friends_FollowFriend", resourceCulture);
            }
        }
        
        internal static string Friends_UnFollowFriend {
            get {
                return ResourceManager.GetString("Friends_UnFollowFriend", resourceCulture);
            }
        }
        
        internal static string Friends_IgnoreFriend {
            get {
                return ResourceManager.GetString("Friends_IgnoreFriend", resourceCulture);
            }
        }
        
        internal static string Friends_ApproveFriend {
            get {
                return ResourceManager.GetString("Friends_ApproveFriend", resourceCulture);
            }
        }
        
        internal static string Draw {
            get {
                return ResourceManager.GetString("Draw", resourceCulture);
            }
        }
        
        internal static string Comments_NoComments {
            get {
                return ResourceManager.GetString("Comments_NoComments", resourceCulture);
            }
        }
        
        internal static string Location_NoPlaces {
            get {
                return ResourceManager.GetString("Location_NoPlaces", resourceCulture);
            }
        }
        
        internal static string Challenge_Conditions {
            get {
                return ResourceManager.GetString("Challenge_Conditions", resourceCulture);
            }
        }
        
        internal static string FriendShip_Accepted {
            get {
                return ResourceManager.GetString("FriendShip_Accepted", resourceCulture);
            }
        }
        
        internal static string FriendShip_Rejected {
            get {
                return ResourceManager.GetString("FriendShip_Rejected", resourceCulture);
            }
        }
        
        internal static string FriendShip_Requested {
            get {
                return ResourceManager.GetString("FriendShip_Requested", resourceCulture);
            }
        }
    }
}
