//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Journey.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Journey.Resources.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Home_LoginAction {
            get {
                return ResourceManager.GetString("Home_LoginAction", resourceCulture);
            }
        }
        
        internal static string Home_WelcomeMessage {
            get {
                return ResourceManager.GetString("Home_WelcomeMessage", resourceCulture);
            }
        }
        
        internal static string Login_CantLoginMessage {
            get {
                return ResourceManager.GetString("Login_CantLoginMessage", resourceCulture);
            }
        }
        
        internal static string Login_CantLoginTitle {
            get {
                return ResourceManager.GetString("Login_CantLoginTitle", resourceCulture);
            }
        }
        
        internal static string UpdateProfile_Finish {
            get {
                return ResourceManager.GetString("UpdateProfile_Finish", resourceCulture);
            }
        }
        
        internal static string UpdateProfile_FirstName {
            get {
                return ResourceManager.GetString("UpdateProfile_FirstName", resourceCulture);
            }
        }
        
        internal static string UpdateProfile_LastName {
            get {
                return ResourceManager.GetString("UpdateProfile_LastName", resourceCulture);
            }
        }
        
        internal static string UpdateProfile_Upload {
            get {
                return ResourceManager.GetString("UpdateProfile_Upload", resourceCulture);
            }
        }
        
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        internal static string UpdateProfile_FirstNameRequired {
            get {
                return ResourceManager.GetString("UpdateProfile_FirstNameRequired", resourceCulture);
            }
        }
        
        internal static string UpdateProfile_ImageRequired {
            get {
                return ResourceManager.GetString("UpdateProfile_ImageRequired", resourceCulture);
            }
        }
        
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        internal static string UpdateProfile_Welcome {
            get {
                return ResourceManager.GetString("UpdateProfile_Welcome", resourceCulture);
            }
        }
        
        internal static string Camera {
            get {
                return ResourceManager.GetString("Camera", resourceCulture);
            }
        }
        
        internal static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string UploadPhoto_Title {
            get {
                return ResourceManager.GetString("UploadPhoto_Title", resourceCulture);
            }
        }
        
        internal static string UploadPhoto_Message {
            get {
                return ResourceManager.GetString("UploadPhoto_Message", resourceCulture);
            }
        }
    }
}
